Traceback (most recent call last):
  File "/Users/ericwais1/rec_io/backend/main.py", line 2, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
